x-env-file: &env_file
  env_file:
    - .env

services:
  sqldb:
    <<: *env_file
    image: mysql:8.3
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    <<: *env_file
    build:
      context: ./codebase/kimai
      dockerfile: Dockerfile
      target: prod

    volumes:
      - data:/opt/kimai/var/data
      - plugins:/opt/kimai/var/plugins

    environment:
      - ADMINMAIL=${ADMIN_EMAIL}
      - ADMINPASS=${ADMIN_PASSWORD}
      - "DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@sqldb/${DATABASE_NAME}?charset=utf8mb4&serverVersion=8.3.0"
    ports:
      - "8089:8001"
    restart: unless-stopped
    depends_on:
      sqldb:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./codebase/kimai/Dockerfile
        - action: sync+restart
          path: ./codebase/kimai/config/
          target: /opt/kimai/config/
        - action: sync+restart
          path: ./codebase/kimai/templates/
          target: /opt/kimai/templates/
        - action: sync+restart
          path: ./codebase/kimai/translations/
          target: /opt/kimai/translations/
        - action: sync+restart
          path: ./codebase/kimai/public/
          target: /opt/kimai/public/
        - action: sync+restart
          path: ./codebase/kimai/src/
          target: /opt/kimai/src/
        - action: rebuild
          path: ./codebase/kimai/assets/

volumes:
  data:
  mysql:
  plugins:
