x-env-file: &env_file
  env_file:
    - .env

services:
  sqldb:
    <<: *env_file
    image: mysql:8.3
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      - kimai_internal

  kimai:
    <<: *env_file
    build:
      context: ./codebase/kimai
      dockerfile: Dockerfile
      target: prod
    
    volumes:
      - data:/opt/kimai/var/data
      - plugins:/opt/kimai/var/plugins

    environment:
      - ADMINMAIL=${ADMIN_EMAIL}
      - ADMINPASS=${ADMIN_PASSWORD}
      - "DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@sqldb/${DATABASE_NAME}?charset=utf8mb4&serverVersion=8.3.0"
    ports:
      - "8089:8001"
    restart: unless-stopped
    depends_on:
      sqldb:
        condition: service_healthy
    networks:
      - caddy
      - kimai_internal
    labels:
      caddy: timesheet.ssa.tg
      caddy.reverse_proxy: "{{upstreams 8001}}"

volumes:
  data:
  mysql:
  plugins:

networks:
  caddy:
    external: true
  kimai_internal:
    driver: bridge
